"""Add field is_completed in Card

Revision ID: a237d6fed850
Revises: ac0e8d183ebd
Create Date: 2026-04-18 02:47:17.821584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a237d6fed850'
down_revision: Union[str, Sequence[str], None] = 'ac0e8d183ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'is_completed')
    # ### end Alembic commands ###
